minor projact/authentication/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path, reverse_lazy, include
from rest_framework import routers

from authentication import views

app_name = 'authentication'

router = routers.DefaultRouter()
router.register(r'user/api', views.UserViewSet, basename='user')

urlpatterns = [
    path('', views.homepage, name='home'),
    path(r'', include(router.urls)),
    path('register/', views.signup, name='register'),
    path('activate/<uidb64>/<token>/', views.activate, name='activate'),
    path('login/', views.signin, name='login'),
    path('logout/', views.signout, name='logout'),
    path('password-reset/',
         auth_views.PasswordResetView.as_view(template_name='authentication/password_reset.html',
                                              email_template_name='authentication/password_reset_email.html',
                                              success_url=reverse_lazy('authentication:password_reset_done')),
         name='password_reset'),
    path('password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(template_name='authentication/password_reset_done.html'),
         name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='authentication/password_reset_confirm.html',
                                                     success_url=reverse_lazy('authentication:password_reset_complete')
                                                     ), name='password_reset_confirm'),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(template_name='authentication/password_reset_complete.html'),
         name='password_reset_complete'),
]

minor projact/pharmacies/urls.py
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from drf_yasg import openapi
from drf_yasg.views import get_schema_view
from rest_framework import permissions

from pharmacies import settings
from shop import views

schema_view = get_schema_view(
    openapi.Info(
        title="Pharmacies API",
        default_version='v0.1',
        description="Our API!",
        terms_of_service="https:/farmacie.pythonanywhere.com",
        contact=openapi.Contact(email="contact@farmacie.pythonanywhere.com"),
        license=openapi.License(name="MIT License"),
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)

urlpatterns = [
                  path('', views.homepage, name='home'),
                  path('admin/', admin.site.urls),
                  path('api-auth/', include('rest_framework.urls')),
                  url(r'^swagger/$', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
                  url(r'^redoc/$', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
                  path('authentication/', include('authentication.urls')),
                  path('shop/', include('shop.urls')),
                  path('timetable/', include('timetable.urls')),
                  path('transfer/', include('transfer.urls')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
admin.sites.AdminSite.site_header = 'Medical Store Admin Panel'
admin.sites.AdminSite.site_title = 'Medical Store Admin Panel'
admin.sites.AdminSite.index_title = 'Admin'

minor projact/shop/urls.py
from django.urls import path, include
from rest_framework import routers

from shop import views

app_name = 'shop'

router = routers.DefaultRouter()
router.register(r'pharmacy/api', views.PharmacyViewSet, basename='pharmacyapi')
router.register(r'category/api', views.CategoryViewSet, basename='categoryapi')
router.register(r'product/api', views.ProductViewSet, basename='productapi')
router.register(r'buyer/api', views.BuyerViewSet, basename='buyerapi')
router.register(r'review/api', views.ReviewViewSet, basename='reviewapi')
router.register(r'contact/api', views.ContactViewSet, basename='contactapi')

urlpatterns = [
    path('', views.homepage, name='home'),
    path(r'', include(router.urls)),
    path('about/', views.about, name='about'),
    path('contact/', views.contact, name="contact"),
    path('pharmacies/', views.pharmacy_list, name='pharmacies_list'),
    path('pharmacies/<id>/', views.pharmacy_detail, name='pharmacies_detail'),
    path('categories/<slug>/', views.categories, name='categories'),
    path('products/', views.product_list, name='products_list'),
    path('products/<id>', views.product_detail, name='products_detail'),
    path('search/', views.search, name='search'),
    path('sellproduct/', views.sell_product, name='sell_product'),
    path('buyitems/', views.buy_items, name='buy_items'),
    path('cart/', views.cart, name='cart'),
    path('resetcart/', views.reset_cart, name='reset_cart'),
    path('payment/', views.payment, name='payment'),
    path('checkout/', views.checkout, name="checkout"),
    path('<id>/addcart/', views.add_cart, name='add_cart'),
    path('<id>/addreview/', views.add_review, name='add_review'),
]

minor projact/timetable/urls.py
from django.urls import path, include
from rest_framework import routers

from timetable import views

app_name = 'timetable'

router = routers.DefaultRouter()
router.register(r'timetable/api', views.TimetableViewSet, basename='timetableapi')

urlpatterns = [
    path('', views.homepage, name='home'),
    path(r'', include(router.urls)),
    path('timetable/', views.view, name='view_timetable'),
    path('timetable/calc', views.calculate, name='calc_timetable'),
]

minor projact/transfer/urls.py
from django.urls import path

from transfer import views

app_name = 'transfer'

urlpatterns = [
    path('', views.homepage, name='home'),
    path('transfer/', views.transfer, name='transfer'),
]

minor projact/shop/models.py
from autoslug import AutoSlugField
from django.contrib.auth.models import User
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models
from django.db.models import CASCADE

from shop.choices import city_choices


class Contact(models.Model):
    id = models.AutoField(primary_key=True)

    name = models.CharField(max_length=250)
    email = models.EmailField()
    subject = models.CharField(max_length=250, blank=True)
    message = models.TextField()

    def __str__(self):
        return self.name

    def __unicode__(self):
        return self.id, self.name, self.email, self.subject, self.message


class Pharmacy(models.Model):
    id = models.AutoField(primary_key=True)
    owner = models.ForeignKey(User, on_delete=CASCADE)

    name = models.CharField(max_length=250)
    image = models.ImageField(upload_to='pharmacy_pics', blank="x.img")
    x = models.IntegerField(default=0, validators=[MinValueValidator(0), MaxValueValidator(100)])
    y = models.IntegerField(default=0, validators=[MinValueValidator(0), MaxValueValidator(100)])
    slot4hMinWeek = models.IntegerField(default=0, validators=[MinValueValidator(0), MaxValueValidator(42)])  # 24/4 * 7
    location = models.CharField(max_length=250, choices=city_choices)
    description = models.TextField(blank=True)
    active = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    def __str__(self):
        return "[" + self.id.__str__() + "] " + self.name

    def __unicode__(self):
        return self.id, self.owner, self.name

    def getSlot4hMinWeek(self):
        return self.slot4hMinWeek

    def getId(self):
        return self.id

    class Meta:
        verbose_name_plural = "Pharmacies"


class Category(models.Model):
    id = models.AutoField(primary_key=True)

    slug = AutoSlugField(populate_from='name')
    name = models.CharField(max_length=250)
    description = models.TextField(blank=True)
    active = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

    def __unicode__(self):
        return self.id, self.name, self.description

    class Meta:
        verbose_name_plural = "Categories"


class Product(models.Model):
    id = models.AutoField(primary_key=True)
    category = models.ForeignKey(Category, on_delete=CASCADE)
    pharmacy = models.ForeignKey(Pharmacy, on_delete=CASCADE)

    slug = AutoSlugField(populate_from='id')
    name = models.CharField(max_length=250)
    image = models.ImageField(upload_to='products')
    description = models.TextField(blank=True, default="Description field")
    brand = models.CharField(max_length=250)
    quantity = models.PositiveIntegerField(default=1)
    price = models.DecimalField(max_digits=10, default=0.0, decimal_places=2)
    shipping_fee = models.DecimalField(max_digits=10, default=0.0, decimal_places=2)
    featured = models.BooleanField(default=False)
    active = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

    def __unicode__(self):
        return self.id, self.name, self.description


class Review(models.Model):
    id = models.AutoField(primary_key=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)

    review = models.CharField(max_length=1000, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    active = models.BooleanField(default=True)

    def __str__(self):
        return self.product.__str__()

    def __unicode__(self):
        return self.id, self.review


class Buyer(models.Model):
    id = models.AutoField(primary_key=True)

    full_name = models.CharField(max_length=250)
    phone = models.CharField(max_length=20)
    city = models.CharField(max_length=250, choices=city_choices)
    address = models.CharField(max_length=250, default="via Vittoria 10")
    product = models.ManyToManyField(Product)

    def __str__(self):
        return self.full_name

    def __unicode__(self):
        return self.id, self.full_name, self.phone

minor projact/shop/forms.py
from django import forms

from shop.models import Product, Buyer, Contact, Review


class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = ['name', 'email', 'subject', 'message']


class SellProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['pharmacy', 'name', 'image', 'category', 'description', 'brand', 'quantity', 'price', 'shipping_fee']


class BuyerDeliveryForm(forms.ModelForm):
    class Meta:
        model = Buyer
        fields = ['full_name', 'phone', 'city', 'address']


class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ['review']

minor projact/shop/templates/shop/base.html
<!DOCTYPE html>
{% load static %}
{% load bootstrap4 %}
<html lang="en">
<head>
    {% comment %} <link rel="shortcut icon" type="image/ico" href="{% static 'favicon.ico' %}"/> {% endcomment %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>{% block title %}Medical Store{% endblock %}</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'css/shop-homepage.css' %}" rel="stylesheet">

</head>

<body>
<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
        <a class="navbar-brand" href="/"><b>Medical Store</b></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive"
                aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
                <li>
                    <form class="form-inline my-2 my-lg-0 mr-4" action="{% url 'shop:search' %}">
                        <input class="form-control mr-sm-2" name="q" type="search" placeholder="Search"
                               aria-label="Search">
                        <button class="btn btn-primary my-2 my-sm-0" type="submit">Search</button>
                    </form>
                </li>
                <li class="nav-item">
                    <a href="{% url 'shop:cart' %}" class="btn btn-success">🛒 {{ request.session.data.count }}</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'shop:home' %}">Home
                    </a>
                </li>

                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown1" role="button"
                       data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Contact</a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown1">
                        {% comment %} <a class="dropdown-item" href="{% url 'shop:about' %}">About</a> {% endcomment %}
                        <a class="dropdown-item" href="{% url 'shop:contact' %}">Contact</a>
                    </div>
                </li>

                <li class="nav-item">
                    {% comment %} <a class="nav-link" href="{% url 'shop:pharmacies_list' %}">Pharmacies</a> {% endcomment %}
                </li>

                {% if user.is_staff %}
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown1" role="button"
                           data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Products</a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown1">
                            <a class="dropdown-item" href="{% url 'shop:products_list' %}">Products</a>
                            <a class="dropdown-item" href="{% url 'shop:sell_product' %}">Sell a product</a>
                            <a class="dropdown-item" href="{% url 'transfer:transfer' %}">Medicine transfers</a>
                        </div>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'shop:products_list' %}">Products</a>
                    </li>
                {% endif %}
{% comment %} 
                {% if user.is_superuser %}
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown1" role="button"
                           data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Timetable</a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown1">
                            <a class="dropdown-item" href="{% url 'timetable:view_timetable' %}">Timetable</a>
                            <a class="dropdown-item" href="{% url 'timetable:calc_timetable' %}">Timetable
                                (Calculate)</a>
                        </div> 
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'timetable:view_timetable' %}">Timetable</a>
                    </li> {% endcomment %}
                {% comment %} {% endif %} {% endcomment %}

                {% if user.is_authenticated %}
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown1" role="button"
                           data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><b>{{ user.username }}</b></a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown1">
                            <a class="dropdown-item" href="{% url 'authentication:logout' %}">Logout</a>
                        </div>
                    </li>
                {% else %}
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                           data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><b>Account</b></a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="{% url 'authentication:register' %}">Register</a>
                            <a class="dropdown-item" href="{% url 'authentication:login' %}?next={{ request.path }}">Login</a>
                        </div>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>
{% block content %}
    <center>{% bootstrap_messages %}</center>
    <!-- Page Content -->
    <div class="container-fluid">

        <div class="row">

            <div class="col-lg-3">
                <br>
                <center><h4>Categories</h4></center>
                {% for category in categories %}
                    <div class="list-group">
                        <a href="{% url 'shop:categories' category.slug %}"
                           class="list-group-item"><b>{{ category.name }}
                            ({{ category.product_set.all|length }})</b></a>
                    </div>
                {% endfor %}

            </div> 

            <!-- /.col-lg-3 -->

            <div class="col-lg-9">
                <div id="carouselExampleIndicators" class="carousel slide my-2" data-ride="carousel">
                    <ol class="carousel-indicators">
                        {% for product in featured_products %}
                            <li data-target="#carouselExampleIndicators"
                                data-slide-to="{{ forloop.counter }}"
                                {% if forloop.counter == 1 %}class="active"{% endif %}></li>
                        {% endfor %}
                    </ol>
                    <div class="carousel-inner" role="listbox">
                        {% for product in featured_products %}

                            <div class="carousel-item {% if forloop.counter == 1 %}active{% endif %}">
                                <br>
                                <b>Featured product: &nbsp</b>
                                <a href="{% url 'shop:products_detail' product.id %}">{{ product.name }}
                                    &nbsp {{ product.price }} ₹</a>
                                <hr>
                                <center><img width="400" height="400" src="/media/{{ product.image }}"
                                             alt="First slide"></center>
                            </div>
                        {% endfor %}
                    </div>
                    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                        <span class="sr-only">Previous</span>
                    </a>
                    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                        <span class="carousel-control-next-icon" aria-hidden="true"></span>
                        <span class="sr-only">Next</span>
                    </a>
                </div>
                <hr>
                <center><h5>All products({{ products_all|length }})</h5></center>
                <hr>
                <div class="row">
                    {% for p in product %}
                        <div class="col-lg-4 col-md-6 mb-4">
                            <div class="card h-100">
                                <center><br><a href="{% url 'shop:products_detail' p.id %}"><img
                                        src="/media/{{ p.image }}"
                                        alt="" width="200"
                                        height="200" alt=""></a>
                                </center>
                                <div class="card-body">
                                    <h4 class="card-title">
                                        <a href="{% url 'shop:products_detail' p.id %}">{{ p.name }}</a>
                                    </h4>
                                    <h5>{{ p.price }} ₹</h5>
                                </div>
                                <center>
                                    <form action="{% url 'shop:add_cart' p.id %}">
                                        <input type="submit" class="btn btn-success" value="Add to cart">
                                    </form>
                                    <br>
                                </center>

                            </div>
                        </div>
                    {% endfor %}
                </div>
                <!-- /.row -->

                <div class="text-center">
                    <span class="step-links">
                        {% if product.has_previous %}
                            <a class="btn btn-outline-info mb-2" href="?page=1">&laquo; First</a>
                            <a class="btn btn-outline-info mb-2" href="?page={{ product.previous_page_number }}">Previous</a>
                        {% endif %}

                        <span class="current">
                            Page {{ product.number }} of {{ product.paginator.num_pages }}
                        </span>

                        {% if product.has_next %}
                            <a class="btn btn-outline-info mb-2" href="?page={{ product.next_page_number }}">Next</a>
                            <a class="btn btn-outline-info mb-2" href="?page={{ product.paginator.num_pages }}">Last &raquo;</a>
                        {% endif %}

                    </span>

                </div>
            </div>
        </div>

    </div>

    <!-- /.col-lg-9 -->
    <!-- /.container -->
{% endblock %}
<!-- Footer -->
<br>
<footer class="py-5 bg-dark">
    <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy Medical Store {% now 'Y' %}</p>
    </div>
    <!-- /.container -->
</footer>

<!-- Bootstrap core JavaScript -->
<script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
<script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

</body>

</html>

minor projact/shop/templates/shop/cart_item.html
{% extends "shop/base.html" %}
{% load bootstrap4 %}
<title>{% block title %}Cart items{% endblock %}</title>

{% block content %}
    <center>
        {% bootstrap_messages %}
        {% for item in products %}
            <br>
            <div class="col-lg-4 col-md-4 mb-4">
                <div class="card h-50">
                    <div class="card-body">
                        <a href="{% url 'shop:products_detail' item.id %}">
                            <img src="/media/{{ item.image }}" width="200" height="100" alt="">
                        </a>
                        <div class="card-body">
                            <h4 class="card-title">
                                <a href="{% url 'shop:products_detail' item.id %}">{{ item.name|title }}</a>
                            </h4>
                            <h5>{{ item.price|floatformat:"2" }} ₹</h5>
                            <h5>Shipping fee: {{ item.shipping_fee }} ₹</h5>
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
        <h5>Items ({{ request.session.data.items|length }})</h5>
        <br>
        {% for item in products %}
            {{ item.name }}: {{ item.price }} ₹
            <br>
        {% endfor %}
        <br>
        <h5>Shipping fee:</h5>
        {% for item in products %}
            {{ item.name }}: {{ item.shipping_fee }} ₹ <br>
        {% endfor %}
        <br>
        <h5>Total price: <b style="color:red;">{{ request.session.data.price }} ₹</b></h5>
        <br>
        <a class="btn btn-success" href="{% url 'shop:buy_items' %}">Procede to checkout</a>
        <br>
        <br>
        <a class="btn btn-success" href="{% url 'shop:reset_cart' %}">Reset cart</a>
        <br>
        <br>
    </center>
{% endblock %}

minor projact/shop/templates/shop/empty_cart.html
{% extends "shop/base.html" %}
{% load bootstrap4 %}
<title>{% block title %}Empty cart{% endblock %}</title>

{% block content %}
    <center>
        {% bootstrap_messages %}
        <br><br>
        <div class="container">
            <h5>You have no items now. Go to <a href="{% url 'shop:products_list' %}"> Shopping!</a></h5>
        </div>
    </center>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
{% endblock %}

minor projact/shop/templates/shop/payment.html
{% extends "shop/base.html" %}
{% load bootstrap4 %}

<title>{% block title %}Sell a product{% endblock %}</title>
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-lg-6 offset-lg-3 col-sm-10 offset-sm-1">
                <div class="card my-5">
                    <div class="card-body">
                        <h4>Select your payment method:</h4>
                        <br>
                        <input type="radio" name="payment" onclick="window.location='{% url 'shop:checkout' %}' "/>
                        Debit Card &nbsp
                        <input type="radio" name="payment" onclick="window.location='{% url 'shop:checkout' %}' "/>
                        Credit Card &nbsp
                        <input type="radio" name="payment" onclick="window.location='{% url 'shop:checkout' %}' "/>
                        PayPal &nbsp
                        <input type="radio" name="payment" onclick="window.location='{% url 'shop:checkout' %}' "/> Cash
                        on delivery
                        <a/>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
{% endblock %}

minor projact/shop/templates/shop/products_detail.html
{% extends "shop/base.html" %}

<title>{% block title %}Details{% endblock %}</title>

{% load bootstrap4 %}
{% block content %}
    <center>
        <center>{% bootstrap_messages %}</center>
        <div class="col-lg-6 col-md-6 mb-6">
            <br>
            <div class="card h-100">
                <div class="card-body">

                    <h4 class="card-title">
                        {{ product.name }}
                    </h4>
                    <center>
                        <img src="/media/{{ product.image }}" alt="" width="200" height="200">
                    </center>
                    <h5>{{ product.price }} ₹</h5>
                    <h5>Shipping fee: {{ product.shipping_fee }} ₹</h5>
                    <h5>Pharmacy: <a
                            href="{% url 'shop:pharmacies_detail' product.pharmacy_id %}">{{ product.pharmacy }}</a>
                    </h5>
                    <h5 class="card-text">Description: {{ product.description }}</h5>
                </div>
            </div>

            <form action="{% url 'shop:add_cart' product.id %}">
                <br>
                <input type="submit" class="btn btn-success" value="Add to cart">
            </form>
            <br>
            <form action="{% url 'shop:buy_items' %}">
                <input type="submit" class="btn btn-success" value=" Buy Now">
            </form>
        </div>
        <br>
        <h4>Reviews ({{ product.review_set.all|length }}) </h4>

        {% for p in product.review_set.all %}
            <div class="col-lg-6 col-md-6 mb-6">
                <div class="card h-25">
                    <div class="card-body">
                        <p class="card-text">{{ p.review }}</p>
                    </div>
                </div>
            </div>
        {% endfor %}
        <hr>
        <div class="col-lg-6 col-md-6 mb-6">
            <form action="{% url 'shop:add_review' product.id %}" method="post">
                {% csrf_token %}
                {% bootstrap_form form %}
                <input type="submit" class="btn btn-success">
            </form>
        </div>
        <br>
    </center>
{% endblock %}

minor projact/shop/templates/shop/products_list.html
{% extends "shop/base.html" %}
{% load bootstrap4 %}
<title>{% block title %}Products{% endblock %}</title>

{% block content %}
    <center>{% bootstrap_messages %}</center>
    <br>
    <center>
        <h5>All items ({{ products_all|length }})</h5>
    </center>
    <hr>
    <div class="row" style="margin-left: 25px;margin-right: 25px;">
        {% for item in products %}
            <div class="col-lg-4 col-md-6 mb-4">
                <div class="card h-100">
                    <a href="{% url 'shop:products_detail' item.id %}">
                        <br>
                        <center>
                            <img width="200" height="200" src="/media/{{ item.image }}" alt="">
                        </center>
                    </a>
                    <div class="card-body">
                        <h4 class="card-title">
                            <a href="{% url 'shop:products_detail' item.id %}">{{ item.name|title }}</a>
                        </h4>
                        <h5>{{ item.price|floatformat:"2" }} ₹</h5>
                    </div>
                    <form action="{% url 'shop:add_cart' item.id %}">
                        <center>
                            <input type="submit" class="btn btn-success" value="Add to cart">
                        </center>
                        <br>
                    </form>
                </div>
            </div>
        {% empty %}
            <div class="card w-100">
                <div class="card-body">
                    <center><h5>Item not available</h5></center>
                </div>
            </div>
        {% endfor %}
    </div>

    {% if products.number %}
        <div class="text-center">
            <br>
            <span class="text-center">
            {% if products.has_previous %}
                <a class="btn btn-outline-info mb-2" href="?page=1">&laquo; First</a>
                <a class="btn btn-outline-info mb-2" href="?page={{ products.previous_page_number }}">Previous</a>
            {% endif %}

                <span class="current">
            Page {{ products.number }} of {{ products.paginator.num_pages }}
            </span>

            <span class="text-center">
            {% if products.has_next %}
                <a class="btn btn-outline-info mb-2" href="?page={{ products.next_page_number }}">Next</a>
                <a class="btn btn-outline-info mb-2"
                   href="?page={{ products.paginator.num_pages }}">Last &raquo;</a>
            {% endif %}
            </span>
            <br>
        </div>
    {% endif %}
{% endblock %}