minor projact/authentication/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path, reverse_lazy, include
from rest_framework import routers

from authentication import views

app_name = 'authentication'

router = routers.DefaultRouter()
router.register(r'user/api', views.UserViewSet, basename='user')

urlpatterns = [
    path('', views.homepage, name='home'),
    path(r'', include(router.urls)),
    path('register/', views.signup, name='register'),
    path('activate/<uidb64>/<token>/', views.activate, name='activate'),
    path('login/', views.signin, name='login'),
    path('logout/', views.signout, name='logout'),
    path('password-reset/',
         auth_views.PasswordResetView.as_view(template_name='authentication/password_reset.html',
                                              email_template_name='authentication/password_reset_email.html',
                                              success_url=reverse_lazy('authentication:password_reset_done')),
         name='password_reset'),
    path('password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(template_name='authentication/password_reset_done.html'),
         name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='authentication/password_reset_confirm.html',
                                                     success_url=reverse_lazy('authentication:password_reset_complete')
                                                     ), name='password_reset_confirm'),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(template_name='authentication/password_reset_complete.html'),
         name='password_reset_complete'),
]

minor projact/pharmacies/urls.py
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from drf_yasg import openapi
from drf_yasg.views import get_schema_view
from rest_framework import permissions

from pharmacies import settings
from shop import views

schema_view = get_schema_view(
    openapi.Info(
        title="Pharmacies API",
        default_version='v0.1',
        description="Our API!",
        terms_of_service="https:/farmacie.pythonanywhere.com",
        contact=openapi.Contact(email="contact@farmacie.pythonanywhere.com"),
        license=openapi.License(name="MIT License"),
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)

urlpatterns = [
                  path('', views.homepage, name='home'),
                  path('admin/', admin.site.urls),
                  path('api-auth/', include('rest_framework.urls')),
                  url(r'^swagger/$', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
                  url(r'^redoc/$', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
                  path('authentication/', include('authentication.urls')),
                  path('shop/', include('shop.urls')),
                  path('timetable/', include('timetable.urls')),
                  path('transfer/', include('transfer.urls')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
admin.sites.AdminSite.site_header = 'Medical Store Admin Panel'
admin.sites.AdminSite.site_title = 'Medical Store Admin Panel'
admin.sites.AdminSite.index_title = 'Admin'

minor projact/shop/urls.py
from django.urls import path, include
from rest_framework import routers

from shop import views

app_name = 'shop'

router = routers.DefaultRouter()
router.register(r'pharmacy/api', views.PharmacyViewSet, basename='pharmacyapi')
router.register(r'category/api', views.CategoryViewSet, basename='categoryapi')
router.register(r'product/api', views.ProductViewSet, basename='productapi')
router.register(r'buyer/api', views.BuyerViewSet, basename='buyerapi')
router.register(r'review/api', views.ReviewViewSet, basename='reviewapi')
router.register(r'contact/api', views.ContactViewSet, basename='contactapi')

urlpatterns = [
    path('', views.homepage, name='home'),
    path(r'', include(router.urls)),
    path('about/', views.about, name='about'),
    path('contact/', views.contact, name="contact"),
    path('pharmacies/', views.pharmacy_list, name='pharmacies_list'),
    path('pharmacies/<id>/', views.pharmacy_detail, name='pharmacies_detail'),
    path('categories/<slug>/', views.categories, name='categories'),
    path('products/', views.product_list, name='products_list'),
    path('products/<id>', views.product_detail, name='products_detail'),
    path('search/', views.search, name='search'),
    path('sellproduct/', views.sell_product, name='sell_product'),
    path('buyitems/', views.buy_items, name='buy_items'),
    path('cart/', views.cart, name='cart'),
    path('resetcart/', views.reset_cart, name='reset_cart'),
    path('payment/', views.payment, name='payment'),
    path('checkout/', views.checkout, name="checkout"),
    path('<id>/addcart/', views.add_cart, name='add_cart'),
    path('<id>/addreview/', views.add_review, name='add_review'),
]

minor projact/authentication/models.py
# Empty

minor projact/authentication/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class UserSigninForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)


class UserSignupForm(UserCreationForm):
    class Meta:
        model = User
        fields = ["username", "email", "password1", "password2"]

minor projact/authentication/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.contrib.sites.shortcuts import get_current_site
from django.core.mail import send_mail
from django.core.paginator import Paginator
from django.shortcuts import render, redirect
from django.template.loader import render_to_string
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from rest_framework import viewsets

from authentication.forms import UserSignupForm, UserSigninForm
from authentication.serializer import UserSerializer
from authentication.tokens import activation_token
from pharmacies import settings
from pharmacies.permission import IsAdmin
from shop.models import Category, Product


def homepage(request):
    products_all = Product.objects.filter(active=True)
    categories = Category.objects.filter(active=True)
    products = Product.objects.filter(active=True).order_by('-created')
    featured_products = Product.objects.filter(featured=True)
    paginator = Paginator(products, 6)
    page = request.GET.get('page')
    products = paginator.get_page(page)
    return render(request, 'shop/base.html',
                  {'products_all': products_all, 'categories': categories, 'product': products,
                   'featured_products': featured_products})


def signup(req):
    if req.method == "POST":
        form = UserSignupForm(req.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.is_active = False
            user.save()
            site = get_current_site(req)
            mail_subject = "Confirmation message"
            message = render_to_string('authentication/activate_mail.html', {
                "user": user,
                'domain': site.domain,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                'token': activation_token.make_token(user)
            })
            to_email = form.cleaned_data.get('email')
            to_list = [to_email]
            from_email = settings.EMAIL_HOST_USER
            send_mail(mail_subject, message, from_email, to_list, fail_silently=True)
            messages.success(req, "Thanks for your registration! A confirmation link has been sent to your mail")
    else:
        form = UserSignupForm()
    return render(req, 'authentication/users_signup.html', {'form': form})


def activate(req, uidb64, token):
    try:
        uid = urlsafe_base64_decode(uidb64).decode()
        user = User.objects.get(id=uid)
    except(TypeError, ValueError):
        user = None
    if user and activation_token.check_token(user, token):
        user.is_active = True
        user.save()
        messages.info(req, 'Your account activated! Now login')
        return redirect("authentication:login")
    else:
        messages.error(req, "Activation link is invalid")


def signin(request):
    if request.method == "POST":
        form = UserSigninForm(request.POST)
        username = form['username'].value()
        password = form['password'].value()
        user = authenticate(username=username, password=password)
        if user:
            login(request, user)
            redirect_url = request.GET.get('next', 'shop:home')
            return redirect(redirect_url)
        else:
            messages.error(request, 'Invalid username or password')
    else:
        form = UserSigninForm()
    return render(request, 'authentication/users_signin.html', {'form': form})


def signout(request):
    logout(request)
    messages.success(request, 'Logged out successfully!')
    return redirect('authentication:login')


"""
API with permissions
"""


class UserViewSet(viewsets.ModelViewSet):
    queryset = User.objects.all()
    serializer_class = UserSerializer
    permission_classes = [IsAdmin]

minor projact/authentication/templates/authentication/activate_mail.html
Hi {{ user.username }}! Thanks for your registration in Pharmacies.
Please click on the link below to activate your account.
http://{{ domain }}{% url 'authentication:activate' uidb64=uid token=token %}

minor projact/authentication/templates/authentication/password_reset.html
{% extends "shop/base.html" %}
{% load bootstrap4 %}

<title>{% block title %}Password reset{% endblock %}</title>

{% block content %}
    <center>{% bootstrap_messages %}</center>
    <br>
    <div class="container">
        <div class="row">
            <div class="col-lg-4 offset-lg-4 col-sm-10 offset-sm-1">
                <div class="card my-5">
                    <div class="card-header text-center">
                        Reset
                    </div>
                    <div class="card-body">
                        <form action="" method="post">
                            {% csrf_token %}
                            {% bootstrap_form form %}
                            <input type="submit" class="btn btn-success text-center w-100 mb-3" value="Reset Password">
                        </form>

                    </div>
                </div>
            </div>
        </div>
    </div>
    <br><br><br><br><br><br><br><br>
{% endblock %}

minor projact/authentication/templates/authentication/password_reset_complete.html
{% extends "shop/base.html" %}
{% load bootstrap4 %}

<title>{% block title %}Password reset complete{% endblock %}</title>

{% block content %}
    <center>{% bootstrap_messages %}</center>
    <br>
    <div class="container">
        <div class="row">
            <div class="col-lg-4 offset-lg-4 col-sm-10 offset-sm-1">
                <div class="card my-5">
                    <div class="card-body">
                        <h5>Password changed successfully!
                            <a href="{% url 'authentication:users_signin' %}">Login</a>
                        </h5>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
{% endblock %}

minor projact/authentication/templates/authentication/password_reset_confirm.html
{% extends "shop/base.html" %}
{% load bootstrap4 %}

<title>{% block title %}Password reset{% endblock %}</title>

{% block content %}
    <center>{% bootstrap_messages %}</center>
    <br>
    <div class="container">
        <div class="row">
            <div class="col-lg-4 offset-lg-4 col-sm-10 offset-sm-1">
                <div class="card my-5">
                    <div class="card-header text-center">
                        Reset
                    </div>
                    <div class="card-body">
                        <form action="" method="post">
                            {% csrf_token %}
                            {% bootstrap_form form %}
                            <input type="submit" class="btn btn-success text-center w-100 mb-3" value="Reset Password">
                            <a href="/" class="float-right small">Home</a>
                        </form>

                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

minor projact/authentication/templates/authentication/password_reset_done.html
{% extends "shop/base.html" %}
{% load bootstrap4 %}

<title>{% block title %}Password reset done{% endblock %}</title>

{% block content %}
    <br>
    <br>
    <br>

    <div class="container">
        <div class="row">
            <div class="col-lg-4 offset-lg-4 col-sm-10 offset-sm-1">
                <div class="card my-5">
                    <center>{% bootstrap_messages %}</center>

                    <div class="card-body">
                        A link has been sent to your email address; please click on that link to reset your password
                    </div>
                </div>
            </div>
        </div>
    </div>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
{% endblock %}

minor projact/authentication/templates/authentication/password_reset_email.html
Hi {{ user.username }}!
Please click on the link below to reset your password.
http://{{ domain }}{% url 'authentication:password_reset_confirm' uidb64=uid token=token %}

minor projact/authentication/templates/authentication/users_signin.html
{% extends "shop/base.html" %}
{% load bootstrap4 %}

<title>{% block title %}Login{% endblock %}</title>

{% block content %}
    <center>{% bootstrap_messages %}</center>
    <div class="container">
        <div class="row">
            <div class="col-lg-4 offset-lg-4 col-sm-10 offset-sm-1">
                <div class="card my-5">

                    <div class="card-header text-center">
                        Login
                    </div>
                    <div class="card-body">
                        <form action="" method="post">
                            {% csrf_token %}
                            {% bootstrap_form form %}
                            <input type="submit" class="btn btn-success text-center w-100 mb-3" value="Login">

                            <center>
                                <a href="{% url 'authentication:password_reset' %}" class="small">Forgot password?</a>
                            </center>
                            <center>
                                <a href="{% url 'authentication:register' %}" class="small">Sign up</a>
                            </center>
                        </form>

                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

minor projact/authentication/templates/authentication/users_signup.html
{% extends "shop/base.html" %}
{% load bootstrap4 %}

<title>{% block title %}Register{% endblock %}</title>

{% block content %}
    <center>{% bootstrap_messages %}</center>
    <div class="container">
        <div class="row">

            <div class="col-lg-6 offset-lg-3 col-sm-10 offset-sm-1">
                <div class="card my-5">
                    <div class="card-header text-center">
                        Sign Up
                    </div>
                    <div class="card-body">
                        <form action="" method="post">
                            {% csrf_token %}
                            {% bootstrap_form form %}
                            <input type="submit" class="btn btn-success text-center w-100 mb-3" value="Register">
                            <a href="{% url 'authentication:login' %}" class="small">Login</a>
                            <a href="/" class="float-right small">Home</a>
                        </form>

                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}